version: '3.8'

services:
  stock-analyst:
    image: fuzanwenn/stock-analyst:latest
    container_name: stock-analyst
    volumes:
      - ./data:/data
    environment:
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    # Override entrypoint for interactive usage
    # command: --help
